const data = {
  success: true,
  data: {
    results: [
      {
        content: {
          title: "What you'll learn",
          description: [
            'Cognitive psychology: An analysis, evaluation, and comparison of major ideas.',
            'The course will examine both personal characteristics and individual differences.',
            'The application of cognitive psychology to everyday events and challenges.',
            'Perception is not reality, although many people incorrectly believe that it is.',
            'Self-awareness as a key to all personal development and social effectiveness.',
            'Adaptability of the mind and the ability to interpret life experiences differently.',
            'A goal setting method that promotes positive thinking and purpose-driven behavior.',
            'A practical framework for mind management and effective emotional regulation.',
            'Simple and effective ways to share what you learn in this course with other people.',
            'And much, much more.',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: [
            'It is not necessary to have prior CBT training or knowledge to join this course.',
            'Students are encouraged to take notes (for self-reflection purposes only).',
            'Students can access this training from anywhere with an internet connection.',
            'You can also listen to the MP3 version if you prefer to learn on the go.',
            'You can access your training course on a tablet, smartphone, or desktop.',
            'Additional PDF materials are provided to enhance your learning experience.',
          ],
          descriptionTitle: 'Description',
          courseDescription:
            "<p><strong>Cognitive Behavioural Therapy (CBT) is a dynamic psychology-based personal growth discipline that offers thought-provoking insights into the relationship between emotions, habits, perceptions, attitudes and behaviours of the human mind.</strong></p><p>A cognitive psychologist investigates how we perceive and interpret information from the environment around us, and how we combine information from that environment with our prior experiences to make decisions about how to respond to our changing environment. This course will offer you insight into the central role cognition plays in our everyday lives.</p><p>This Cognitive Behavioural Therapy (CBT) Practitioner Training is a comprehensive learning experience that’s firmly rooted in time-honoured cognitive psychology. As you take this course, you will gain a clear understanding of how the mind works, as well as the opportunity to raise your self-awareness, shape inner resilience, and enhance your mental well-being.</p><p>This course covers the major themes of cognitive psychology, such as perception, mind management, decision making, and more. During this course, you will learn how CBT can assist with stress reduction, confidence, motivation, and life transitions. This course offers insights into human nature by blending cognitive psychology with valuable life principles.</p><p>Cognitive Behavioural Therapy Practitioner Training offers you a solid basis for self-definition where they can evaluate their general outlook on life. Moreover, this training will introduce you to numerous psychological concepts which will facilitate your personal growth as you learn how to make wise decisions about how you allocate your time, energy and resources.</p><p><br></p><p><strong>The following are some of the topics you will learn during this training:</strong></p><ul><li><p>Cognitive psychology: An analysis, evaluation, and comparison of major ideas.</p></li><li><p>The course will examine both personal characteristics and individual differences.</p></li><li><p>The application of cognitive psychology to everyday events and challenges.</p></li><li><p>Perception is not reality, although many people incorrectly believe that it is.</p></li><li><p>Self-awareness as a key to all personal development and social effectiveness.</p></li><li><p>Adaptability of the mind and the ability to interpret life experiences differently.</p></li><li><p>A goal setting method that promotes positive thinking and purpose-driven behavior.</p></li><li><p>And much, much more.</p></li></ul><p><br></p><p>The psychology of cognition covers a wide range of topics, including knowledge, perception, activity, problem-solving, personal development, and mental resilience. This course covers the most important concepts and themes in modern cognitive psychology, such as the human tendency to interpret, explain, and find meaning in life's everyday experiences.</p><p>The course consists of over 32 hours of formal instruction and practical discussion. In each section of the course, you will learn practical life skills as well as theoretical knowledge and a disciplined approach to cultivating self-awareness which includes self-reflection. The instructor has over a decade of experience in teaching CBT and modern applied psychology.</p><p>Within the subject matter of this training, a variety of established psychology-based frameworks are used (including some that are unique to this program). You will be provided with all of the knowledge that you need to integrate the fundamental teachings of CBT into every relevant aspect of your life by enrolling in this on-demand CBT Practitioner Training.</p><p>We will provide you with bite-sized modules in this course that are easy to understand and apply. The flexibility to learn anywhere, anytime, on any device means you are in total control. The course is endorsed by the Academy of Modern Applied Psychology and includes all the relevant topics to ensure you gain a clear comprehension of the topic.</p><p><em>“An excellent course if you want to practice cognitive psychology - the additional resources are also extremely valuable and I cannot recommend this course enough.”</em> - Fraser Hemsworth</p><p><strong>This training is part of a larger curriculum of professional development training resources, designed by Kain Ramsay Ltd, and hosted within the Achology community peer-learning environment. The training course is accompanied by a 30-day money back guarantee, so if you're not happy with the format, you can get your money back - no questions asked.</strong></p>",
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'People in roles of social or occupational influence, such as parents, managers/leaders.',
            'Individuals who want to increase in self-awareness and are inspired by personal growth.',
            'Experienced CBT practitioners or psychologists who want to broaden their perspective.',
            'Students with an interest in general psychology will find this course particularly interesting.',
            'The course can be taken independently or in tandem with another Achology training.',
            'People from all cultures will benefit from the lessons and insight offered in this course.',
          ],
        },
        id: 'course-cognitive-behavioural-therapy-online-course-cbt-practitioner-course',
        category: 'Mental Health',
        description:
          'Become a Certified Cognitive Behavioural Therapy (CBT) Practitioner and elevate your understanding of human behaviour.',
        image: 'https://img-c.udemycdn.com/course/240x135/1091520_9b90_11.jpg',
        instructor: 'Created by Kain Ramsay, The Academy of Modern Applied Psychology',
        lastUpdated: 'Last updated 10/2022',
        slug: 'course/cognitive-behavioural-therapy-online-course-cbt-practitioner-course/',
        tag: 'CBT Cognitive Behavioral Therapy',
        title: 'Cognitive Behavioural Therapy (CBT) Practitioner Course',
        index: '6353ad2dd4a540a0a48940d2',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Understand what the Macronutrients are and the role they play in our bodies',
            'Understand the role Micronutrients, Fiber, Probiotics & Water play in our bodies',
            'Understand Energy Balance. Figure out easy ways to determine BMR, TDEE',
            'Learn the Top Carbohydrates/Proteins/Fat sources and figure out their estimated daily requirements',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['Passion for Nutrition', 'Willingness to help and motivate others to eat healthy'],
          descriptionTitle: 'Description',
          courseDescription:
            "<p><strong>Updated: Nov 2021</strong></p><p>A Nutrition Career Guide (50 Pages) to help anyone wanting to start their Nutrition Career. </p><p><strong>Updated: Nov 20</strong></p><p>Newly Created Audio and Video Presentation for a more engaging experience </p><p>20% more content added especially related to the Micronutrient Content. </p><p><strong>Updated: Nov. 19</strong></p><p>-Added a Starter Pack- 30+ Minutes</p><p>-Added another Accreditation Authority: IAOTH-The International Association of Therapists</p><p>-New Professional Certificate Design (different from Udemy)</p><p><strong><em>Now earn your Internationally&nbsp;Accredited Diploma in Nutrition&nbsp;accredited&nbsp;by The CPD Standards Certification Service, which is an independent body that ensures qualifications are in line with the most current professional standards.</em></strong></p><p>This means this course&nbsp;comply with universally accepted principles of Continual Professional Development (CPD) and have been structured to meet the criteria of personal development plans.<br></p><p>&nbsp;CPD certification means that the content and structure of the courses have been independently assessed and approved for multi-disciplinary and industry-wide continuing personal and professional development purposes.<br></p><p><strong>Pass Mark</strong>: 50% to secure your certificate!</p><p><strong>Course Pre-requisite</strong>: None</p><p><strong>Course Duration</strong>: 1-4 weeks</p><p><strong>Course Lectures:</strong></p><p>See Below.&nbsp;</p><p><strong>Quizzes &amp; Graded Exam:</strong></p><p>Graded Exam&nbsp;</p><p><strong>Certificate:</strong></p><p>Internationally Accredited by CPD (Details in the course)</p><p><strong>Course &amp; Exam Location</strong>: Online</p><p><strong>Course Description&nbsp;</strong></p><p>We are facing an obesity epidemic where almost 2 billion people worldwide are overweight and 650 million are obese. This is hugely contributing to a significant increase in chronic diseases like type-2 diabetes and heart related conditions. These chronic ailments are largely preventable by following a healthy diet combined with an active lifestyle.</p><p>This diploma in nutrition will be of great interest to all learners and healthcare professional who would like to learn the fundamentals of nutrition science. It provides an in-depth look into macronutrients and micronutrients and understand how they are essential for our bodies to grow and remain healthy.</p><p><strong>Module-1: Introduction to Nutrition</strong>&nbsp;will start off by discussing nutrition and nutrients. You will understand the concept of Energy Balance, BMR [Basal Metabolic Rate], TDEE [Total Daily Energy Expenditure], figure out how to calculate them using certain equations and formulas.&nbsp;\n</p><p><strong>Module-2: Macronutrients</strong>&nbsp;will dive deep into three macronutrients i.e. carbohydrates, proteins and fats. We will learn everything about them, including their classifications, types, food sources and their functions and requirements.</p><p><strong>Module 3: Micronutrients&nbsp;</strong>will discuss fat-soluble and water soluble vitamins, minerals, fiber, probiotics and water. We will do an in-depth discussion in the important functions that these micronutrients play in human body, their best food sources and symptoms which may occur in case their is a deficiency of a respective nutrient in our diet. You will be also be provided a table, that depicts their daily values, adequate limit, and upper tolerable limits.</p><p>Along with visually pleasing lecture slides, you will find a voiceover presentation which explains all the slides in detail plus you will find the accompanying script in case you want to read [Helpful for people who are hearing impaired]</p><p><strong>Module 4</strong>&nbsp;will provide you with 14 Nutritional Guidelines and 15 Healthy Snack Ideas and at least few diet plans both vegetarian and non-vegetarian.</p><p><br></p><p>###IMPORTANT###</p><p>We offer a CPD Certificate which is different from the Udemy's Certificate of Completion. If you want your CPD Certificate from us, you are required to provide your full name and email-address. Your details will remain confidential with us. <br></p><p><strong>Who is the course for?</strong></p><p>-Anyone who wants to learn how to eat healthy and understand the fundamentals of nutritional science</p><p>-Health &amp; Fitness Professionals who want to help their clients with general nutrition tips/guidelines</p><p><strong>By the end of this course, what will you Learn?</strong>\n</p><p>-Understand what the Macronutrients are and the role they play in our bodies</p><p>-Understand the role Micronutrients, Fiber, Probiotics &amp; Water play in our bodies</p><p>-Understand Energy Balance. Figure out easy ways to determine BMR, TDEE</p><p>-Learn the Top Carbohydrates/Proteins/Fat sources and figure out their estimated daily requirements.</p><p>&amp; much more!</p><p>Lastly, you there is Bonus section which provides ‘additional’ readings and resources to in-case you want more in-depth understanding of the concepts provided.</p>",
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone who wants to learn how to eat healthy and understand the fundamentals of nutritional science',
            'Health & Fitness Professionals who want to help their clients with general nutrition tips/guidelines',
          ],
        },
        id: 'course-internationally-accredited-diploma-certificate-in-nutrition',
        category: 'Nutrition & Diet',
        description: 'Learn how to eat healthy and understand the fundamentals of nutrition science',
        image: 'https://img-c.udemycdn.com/course/240x135/1504862_475f_4.jpg',
        instructor: 'Created by Akash Sehrawat, Fabulous Body, Teaching Assistant',
        lastUpdated: 'Last updated 11/2021',
        slug: 'course/internationally-accredited-diploma-certificate-in-nutrition/',
        tag: 'Nutrition',
        title: 'Internationally Accredited Diploma Certificate in Nutrition',
        index: '6353ad2dd4a540a0a48940f8',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Understand the psychology behind how to use therapeutic art to access the subconscious mind and change limiting patterns and beliefs.',
            'Use therapeutic art techniques with your clients to help them increase their happiness, manage their emotions in a positive way, and feel more confident!',
            'Use therapeutic art techniques to help your life coaching clients reduce their stress and heal emotional pain.',
            'Use therapeutic art techniques to help your life coaching clients increase their self-awareness, intuition, and self-expression.',
            'Help your clients create art without self-judgment. Use therapeutic art processes for helping your clients create tangible picture of their visions and dreams.',
            'Use proven step-by-step art processes including mandalas, affirmation art, vision/dream boards, guided meditation, and more!',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['Ability to print course material.'],
          descriptionTitle: 'Description',
          courseDescription:
            '<p><strong>Students who complete this course will receive an official life coach CERTIFICATION from Transformation Academy. <em>This course is also accredited by internationally recognized Continuing Professional Development Standards Agency </em>(Provider No: 50134), and 10 CPD or CEU credits are available upon request. Details for how to request the official certification and optional 10 CPD/CEU credits will be provided at the end of the course.</strong></p><p><strong>+++++++++++++++++++++++++++++++++++++++++++++++</strong></p><p><strong><em>We are top Udemy instructors in the personal development&nbsp;category. Our courses have been taken by over 700,000+ happy students from 200 countries.</em></strong></p><p><strong><em>This course is taught by 3 instructors who are experts in the fields of psychology and therapy.</em></strong></p><p><strong><em>We have a thriving community in the course and we are actively involved and answer questions within 24h.</em></strong></p><p><strong><em>The course also has a thriving Facebook networking group.&nbsp;</em></strong></p><p><strong>+++++++++++++++++++++++++++++++++++++++++++++++</strong></p><p><strong><em>&lt;&lt;&lt;&lt;If you would prefer to take a version of this course that is meant for individuals, not life coaches, check out the "Therapeutic Art for Healing, Happiness and Stress Reduction" course.&gt;&gt;&gt;</em></strong></p><p><br></p><p>Do you want to help your clients heal, reduce stress, and experience more joy, peace, and harmony?&nbsp; &nbsp;&nbsp; </p><p>Do you want to help your clients increase their creativity, intuition, or self-expression?\n\n&nbsp; </p><p>Therapeutic art is a powerful tool that you can use as a life coach to <strong>help your clients unlock the power of their subconscious mind</strong>, allowing them to:\n\n&nbsp; </p><ul><li><p>Release pain\n\n&nbsp; </p></li><li><p>Process emotions\n\n&nbsp; </p></li><li><p>Find clarity and meaning\n\n&nbsp; </p></li></ul><p>Art has been used throughout human history to express the depths of human experience because our minds understand the abstract or symbols at a deeper level than language, and now you can add this ancient tool to your <strong>life coaching toolbox</strong>!\n\n&nbsp; </p><p>This course is designed teach you the <strong>psychology</strong> behind how and why art is such a powerful tool for improving wellbeing! You will also learn a variety of therapeutic art processes and exercises that you can use to <strong>help your clients:</strong>\n\n&nbsp; </p><ul><li><p>Improve their self-expression\n\n&nbsp; </p></li><li><p>Uncover and release outdated patterns\n\n&nbsp; </p></li><li><p>Heal past emotional pain\n\n&nbsp; </p></li><li><p>Tune into their intuition\n\n&nbsp; </p></li><li><p>Explore their deepest dreams and desires\n\n&nbsp; </p></li></ul><p>The therapeutic art life coaching process you will learn will include powerful ancient art designs for meditation and self-exploration, such as <strong>mandalas</strong>, as well as modern day artistic approaches for goal setting and manifestation, such as <strong>vision boards</strong> or dream boards.\n\n&nbsp; </p><p>Plus, you’ll receive other powerful processes to use with your clients, including <strong>journaling</strong>, guided <strong>meditation</strong>, and art for <strong>stress reduction</strong>.\n\n&nbsp; </p><p>You’ll also learn supplemental psychology processes for helping your clients <strong>unlock the power of their minds</strong> by:\n\n&nbsp; </p><ul><li><p>Changing their thoughts and beliefs\n\n&nbsp; </p></li><li><p>Using affirmations to increase their confidence\n\n&nbsp; </p></li><li><p>Using visualization to rewire their brain and transform their life&nbsp; &nbsp; </p></li></ul><p>\n\n\n\n</p><p>This life coach certification is designed to be used with adults, but the powerful therapeutic art tools you will learn can be used with any age group. In fact, <strong>ANYONE can benefit from these art exercises—NO ARTISTIC ABILITY IS REQUIRED!</strong> \n\n&nbsp; </p><p>You can use these processes with:</p><ul><li><p>One-on-one life coaching clients \n\n&nbsp; </p></li><li><p>Group life coaching programs\n\n&nbsp; </p></li><li><p>Facilitating workshops \n\n&nbsp; </p></li></ul><p><strong>Become a Certified Therapeutic Art Life Coach</strong>, or simply add these powerful tools to your current life coaching practice. \n\n&nbsp; </p><p>&nbsp;\n\n&nbsp; </p><p><strong>Upon completion, students will receive an official <em>Therapeutic Art Life Coach Certificatio</em>n from Transformation Services, Inc.<br></strong></p><p><strong>There is a non-coaching version of this course for those that are trying to take the course for personal reasons. That course has the same content as this course without the extra content to learn how to use it with your clients.&nbsp; Therefore, do not register for both courses. </strong></p><p><br></p><p>So, are you ready to help your clients to create more joy, peace, and harmony in their life using therapeutic art? If so enroll now, we look forward to seeing you in the course!&nbsp; &nbsp;&nbsp; </p><p><strong>Guarantee:</strong> We know you will love this course. However, we offer a no-questions-asked 30-day money-back guarantee if the course does not meet your needs for any reason.&nbsp; \n&nbsp; </p><p><strong>MEET THE INSTRUCTORS:</strong>\n\n&nbsp; </p><p>This course is taught by three experts in the fields of life coaching, personal development, psychology and psychoanalysis. Our varied experience and perspectives add depth and variety to the program. \n\n&nbsp; </p><p>Instructors <strong>Joeel &amp; Natalie Rivera</strong> have over a decade in the life coaching field. The have a background in social services, psychology, education and as entrepreneurs. Joeel has a Masters’ in Counseling and is completing his dissertation for his Ph.D. in Psychology, with a focus on happiness. They have over <em>300,000+</em><strong><em> </em></strong>students from 195 countries.&nbsp; &nbsp; </p><p><strong>Victoria Hawkins</strong> is a Licensed Clinical Social Worker, psychotherapist, artist, yoga and dance instructor, and workshop facilitator. She has been working with students and clients of all ages for over 20 years; incorporating art, creative movement, wisdom teachings, creative writing, psychotherapy and mindfulness meditation.&nbsp; &nbsp;&nbsp;</p><p><em>DISCLAIMER: The content in this course is provided for educational purposes only. This course has not been accredited by any state, national, international accreditation association or educational board. All certificates issued by Transformation Academy are certified by Transformation Services, Inc. only. No certificate or item sold on this website is intended to duplicate or bear a resemblance to that of any items issued by a state or federal governmental agency or any other academic organization or society.</em></p><p><br></p><p><br></p><p>Copyright ©️ Transformation Services, Inc. | All Rights Reserved</p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'You want to help your clients express themselves, heal, or increase their happiness, creativity or confidence',
            'You are (or want to be) a LIFE COACH',
            'You are a counselor, therapist, life coach, speaker, teacher or other professional who wants to add powerful art therapy life coaching tools to your toolbox',
            'You like to have a structure to follow and step-by-step system with proven results',
            'You want to be able to give clients something concrete that they can work on',
            'You want to expand your credibility through being a Certified Therapeutic Art Life Coach',
          ],
        },
        id: 'course-art-therapy-life-coach-certification',
        category: 'Mental Health',
        description:
          'Therapeutic Art: Help Clients Heal, Reduce Stress & Manifest Dreams with Mandalas, Affirmations, Vision Boards & More',
        image: 'https://img-c.udemycdn.com/course/240x135/1746608_d226_4.jpg',
        instructor: 'Created by Joeel & Natalie Rivera, Victoria Hawkins, Transformation Services',
        lastUpdated: 'Last updated 10/2022',
        slug: 'course/art-therapy-life-coach-certification/',
        tag: 'Art Therapy',
        title: 'Therapeutic Art Life Coach Certification  (Accredited)',
        index: '6353ad2dd4a540a0a48941bf',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Know your habitual, automatic reactions to stress',
            'Access the resources of mindfulness and compassion',
            'Make more conscious choices in pressured situations',
            'Grow stronger and wiser right in the very midst of stress',
            'Experience a larger, more empowered and joyful way of being in the world',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['There is no prerequisite to taking this course.'],
          descriptionTitle: 'Description',
          courseDescription:
            '<p>When stressful events come our way, evolution has hardwired us to go into the fight-flight-freeze response. This automatic process served us well in surviving across millennia as a species, but in modern life, unconscious reactivity often is counterproductive and even harmful to the things that matter most to us. </p>\n\n<p>In reality, stress – the actual experience of tension, of demand – though it may be uncomfortable, doesn’t have to be a problem. In fact, a certain amount of stress is necessary to bring out our full intelligence, creativity and care. It’s the essential ground for us to wake up to our own full potential: to who we really are. When we cultivate our capacities for mindfulness and compassion, meeting the challenges of life actually helps us grow mentally &amp; emotionally stronger, as well as physically healthier thanks to reduced inflammation responses.</p>\n\n\n\n\n\n\n\n<p>A critical inquiry for us as humans is: When we get triggered and reactive, how do we shift from flight-flight-freeze, into “attend and befriend”?&nbsp; This is the evolutionary shift that reconnects us to ourselves and each other; and, globally, can help to end violence and heal our precious earth.</p>\n\n\n\n\n\n\n\n<p>In this short course packed with practical teachings and scientifically validated meditation exercises, students will work directly with their real-life negative patterns and learn to relate to stress with an empowering, clear and caring presence.</p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone who feels plagued by stress',
            'Anyone troubled by ongoing, mild-to-moderate anxiety',
            'Anyone caught in repeating destructive behaviors',
            "Anyone who'd like to handle relationship challenges more successfully",
          ],
        },
        id: 'course-flourishing-in-stressful-times-with-tara-brach',
        category: 'Meditation',
        description:
          'Transform anger & anxiety into resilience & creative energy through the practice of compassion, mindfulness & meditation',
        image: 'https://img-c.udemycdn.com/course/240x135/1426094_79c4_2.jpg',
        instructor: 'Created by Tara Brach, Ph.D.',
        lastUpdated: 'Last updated 8/2021',
        slug: 'course/flourishing-in-stressful-times-with-tara-brach/',
        tag: 'Stress Management',
        title: 'Flourishing in Stressful Times - with Tara Brach',
        index: '6353ad2dd4a540a0a4894136',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Start making your first herbal remedy from day one. It is easier than you think!',
            'Learn life-changing skills. The course has everything you need to know in one place including information you will not find anywhere else.',
            'Details of over 20 of the most important plants used in herbal medicine plus making tinctures, teas, oils, salves, honeys, syrups, compresses and poultices.',
            'Step-by-step instruction so you feel confident in making and using herbal medicine without being overwhelmed.',
            'Find herbs everywhere, no matter where in the world you live – stores, online, backyard, garden, community.',
            'Learn from Udemy’s top qualified herbal instructor. She is consistently available to answer your course related questions.',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['This is an introductory course for anyone. Supplies and ingredients are minimal.'],
          descriptionTitle: 'Description',
          courseDescription:
            '<p><strong>CURIOUS ABOUT HERBAL MEDICINE?</strong></p><p>Start making your first herbal remedy from day one. It is easier than you think!</p><p>No matter where in the world you live, you have easy access to valuable medicinal plants. Over 28,000 students have greatly benefited from this online herbalism course. For beginners, the course has been life changing. For those who already have some experience, it has filled in the gaps. Imagine everything you need to get started in one place!</p><p><strong>Here’s what students have to say:</strong></p><p><em>★★★★★ "Wonderful course that is taught by an experienced herbalist. This is THE place to start when you want to be a herbalist." – Tessa H</em></p><p><em>★★★★★ "Very good information that I have not been able to find anywhere else. Very easy to understand.” – Carolyn E</em></p><p><em>★★★★★ "It helps to see the instructor really performing the tasks - a picture (or video here) is worth a thousand words. There are many helpful details that would not even occur to me to ask about. The Q&amp;A section works great! I am immediately putting the new knowledge to practice, referring back to the lessons for details. Thank you!" – Zdenka D</em></p><p><em>★★★★★ "This was an excellent beginner course for me! It provided a gold mine of information without feeling overwhelming. I greatly enjoyed the course. I enjoyed how the sections where clearly laid out making them easy to follow.” – Kodili C</em></p><p><em>★★★★★ "I have been wanting to learn herbs for a long time but have always felt intimidated. This course was so awesome. It gave me courage and I learned more from her in this one class than I have from anyone else.” – Cindy B</em></p><p><strong>There is a growing movement in herbalism. You can be a part of it.</strong></p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;You will gain better health by knowing which plants to use and how to use them.</p><p>&nbsp; &nbsp; <strong>·</strong>&nbsp; &nbsp; &nbsp;You will be more self-reliant without the need for many pharmaceuticals.</p><p>&nbsp; &nbsp; <strong>·</strong>&nbsp; &nbsp; &nbsp;You will take a central role in your wellbeing as well as those you love.</p><p>&nbsp; &nbsp; <strong>·</strong>&nbsp; &nbsp; &nbsp;You will never find better quality herbal medicine than what you make yourself.</p><p>By the end of the course you will feel confident in using plant medicines. You will not only understand which plants to use, but why they work in the way they do. With step-by-step instruction, there are no worries about being overwhelmed. You will also be able to refer back to the course material any time you like.</p><p><strong>Your instructor, Elizabeth Heck</strong> has 25 years of experience in working with plant medicines. She is by far, Udemy’s most qualified herbal instructor. Rest assured, you’re in good hands. With an extensive teaching background, she knows how to guide you through your herbal learning journey with ease. Even better, she is there for you throughout the course to answer any of your questions. That’s incredible value!</p><p><strong>Plants provide some of our most valuable medicine</strong></p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Herbs are readily available to everyone, whether you grow, harvest or purchase them.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Herbs can be helpful for specific diseases, prevention, energy and vitality.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Herbs can support other forms of medicine and ways of healing.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Herbal medicines are easy and inexpensive to make as well as easy to use.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Herbs are very effective and safe with good instruction.</p><p>Plants have been successfully used as medicine throughout history. Currently, the World Health Organization states that more than 80% of people on earth use herbs as their primary form of medicine.</p><p>Discover this important mode of healing and learn how you can incorporate herbs into your life for optimum health.</p><p><strong>Here is what you’ll get from the course:</strong></p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Practical understanding of what herbalism is and how it works.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Know how to make tinctures, teas, oils, salves, honeys, syrups, compresses and poultices.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;Details of over 20 of the most commonly used medicinal herbs.</p><p>&nbsp; &nbsp; <strong>·&nbsp; </strong>&nbsp; &nbsp;A necessary foundation if you decide to move forward with an herbal career.</p><p><strong>Why is this course not Accredited?</strong></p><p>Nearly every online course (unless it is a large university) that claims to be accredited, actually is not. These are simply fake accreditations from real-looking websites used as a marketing scam in order to sell more courses. Elizabeth, as with any experienced herbalist, teaches with ethics and integrity and absolutely will not be deceitful for marketing sake. Rather, her students are sincerely respected and honored. Therefore none of her courses claim to be accredited.</p><p><strong>More of what students have to say:</strong></p><p><em>★★★★★ “I have always enjoyed making home remedies and seeing the effects of them on my family, and now that I’ve learned the different medicinal purposes for a few herbs and treatments here and how to use them in their proper context I can move on to helping my family feel and live better even the more. Thank you for the opportunity to learn with you Mrs Heck I enjoyed every moment of the class and felt like I was sitting in your kitchen and walking through your garden with you. For me that would be a sheer delight. Kindest regards” – Jaazer</em></p><p><em>★★★★★ "I found Elizabeth Heck to be very engaging and informative with this course. As someone who has experimented with herbal remedies, I felt that I have learned even more through her instruction. With her step-by-step demonstration on how to create different tinctures, oils, salves, etc. I have found it to be an improvement rather than stumbling around my kitchen trying to figure it out myself. I highly recommend her course and am looking forward to enrolling in more taught by Elizabeth Heck.” – Jodi C</em></p><p><em>★★★★★ "I loved this course. It really validated the interest I have in herbalism. After completing this course, I am now more than ever interested in becoming a herbalist. Thank you for this course.” – Anna S</em></p><p><strong>You have lifetime access to the course so you can take as long or short as you wish to go through the material. You can replay the videos at anytime using the course as an ongoing reference. You also have a 30 day money back guarantee.</strong></p><p><strong>BE SURE TO ENROLL NOW!</strong></p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Those interested in preventative care as well as those interested in caring for themselves and their loved ones.',
            'Those interested in empowering their health and wellbing.',
            'Those interested in herbalism and herbal medicine.',
          ],
        },
        id: 'course-herbalism-medicine-making',
        category: 'General Health',
        description:
          'Take charge of your health with herbal medicine. Using herbs and natural holistic medicine is easy, effective and safe.',
        image: 'https://img-c.udemycdn.com/course/240x135/985790_5813_2.jpg',
        instructor: 'Created by Elizabeth Heck',
        lastUpdated: 'Last updated 3/2022',
        slug: 'course/herbalism-medicine-making/',
        tag: 'Herbalism',
        title: 'Herbalism :: Introduction & Medicine Making Certificate',
        index: '6353ad2dd4a540a0a48941ca',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Earn your CPD Certificate',
            'Design weight loss & muscle growth diets',
            'Help others lose fat & build muscle',
            'Assess clients and determine fitness levels',
            'Understand the fundamentals of proper nutrition',
            'Build and grow a coaching business (online or in person)',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: [
            'Willingness to help and motivate others to eat health & diet correctly',
            'Passion for nutrition',
          ],
          descriptionTitle: 'Description',
          courseDescription:
            '<p><strong>&gt;&gt;&gt;THIS COURSE IS CPD ACCREDITED. COMPLETE IT AND YOU AUTOMATICALLY EARN YOUR CERTIFICATION &amp; 10 CREDITS&lt;&lt;&lt;</strong></p><p><strong>Learn How To Become A Diet Coach, Work With Clients And Grow&nbsp;Your&nbsp;Fitness Coaching&nbsp;Business </strong></p><p>Hi,&nbsp;I\'m Felix Harder fitness coach and certified nutritionist.&nbsp;My "Diet And Nutrition Coach Certification"&nbsp;is designed&nbsp;<strong>for anyone&nbsp;who wants to coach others about dieting - be it&nbsp;to lose weight, build muscle or healthy eating.</strong></p><p>In this course I will take you through the process of <strong>becoming a nutrition expert&nbsp;step by step</strong>. You will learn everything you need to know about the fundamentals of good meal plans and how to design your very own for you or your clients.&nbsp;</p><p>Researching and gathering all the knowledge you need to coach others takes a lot of time, so I created this course as a <strong>complete program to teach you everything there is to know about dieting &amp; fitness</strong>:</p><p>- Nutrition Theory (Calories, Macronutrient, Micronutrients etc.)<br>- Meal Planning (Create diets for weight loss &amp; muscle growth)<br>- Working with clients (assessing their eating habits &amp; helping them see results fast)</p><p><strong>Here Is What\'s Inside The Program: </strong></p><p><strong>Nutrition Theory</strong></p><ul><li><p><em>Everything You Need To Know About Calories,&nbsp;Protein, Carbs &amp; Fat</em></p></li><li><p><em>How To Determine Your Optimal Calorie Intake</em></p></li><li><p><em>Energy Metabolism</em></p></li><li><p><em>Protein, Carb &amp; Fat Digestion&nbsp;</em></p></li></ul><p><strong>Helping Clients Lose Weight</strong></p><ul><li><p><em>How To&nbsp;Create Diets For Weight Loss</em></p></li><li><p><em>How To Take Diet Breaks Correctly</em></p></li><li><p><em>How To Break Through Weight Loss Plateaus</em></p></li><li><p><em>Is Starvation Mode Real?</em></p></li><li><p><em>Explaining Unexpected Weight Changes</em></p></li></ul><p><strong>Helping Clients Build Muscle</strong></p><ul><li><p><em>How To&nbsp;Create Diets For Muscle Gains</em></p></li><li><p><em>When To Eat For Optimal Results (Pre- &amp; Post-Workout Meals)</em></p></li><li><p><em>How Many Meal&nbsp; Should You Eat?</em></p></li><li><p><em>The Best Foods For Muscle Growth</em></p></li></ul><p><strong>Diet Trends&nbsp;Explained:</strong></p><ul><li><p><em>Gluten Free</em></p></li><li><p><em>Low Carb</em></p></li><li><p><em>Paleo Dieting</em></p></li><li><p><em>Intermittent Fasting</em></p></li><li><p><em>Vegan Dieting</em></p></li><li><p><em>Ketogenic Diets</em></p></li></ul><p><strong>Vitamins &amp; Minerals:</strong></p><ul><li><p><em>Vitamins A - K Explained (How Much Do You Need)</em></p></li><li><p><em>Minerals: Calcium - Zinc</em></p></li><li><p><em>The Ideal Water Intake</em></p></li><li><p><em>Why You Should Avoid Multivitamins</em> </p></li></ul><p><strong>Supplements (Find Out If You Really Need Them):</strong></p><ul><li><p><em>Whey Protein</em></p></li><li><p><em>Creatine</em></p></li><li><p><em>Fish-Oil</em></p></li><li><p><em>BCAAs</em></p></li><li><p><em>Glutamine</em></p><p><br></p></li></ul><p>The diet and nutrition certification is not just for professionals but also for beginners who want to improve their own fitness level. <strong>You don’t need to be a dietician (dietitian)</strong> <strong>or have to have any students yet and all you need is an interest in fitness to get started</strong>.</p><p>The nutrition for beginners program is made up of multiple downloadable worksheets, eBooks and other printable resources. If you sign up you get access to all of them so you can <strong>study anywhere and at anytime</strong>.&nbsp;</p><p>Remember, there is a 30-day 100% money-back guarantee. There is no reason to hesitate. Enroll now, see if you enjoy the course, and&nbsp;<strong>start learning today</strong>!</p><p><br></p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone intersted in coaching others',
            'Anyone wanting to learn how to design diets & meals plans',
            'Anyone wanting to grow their fitness business (online or in person)',
          ],
        },
        id: 'course-diet-nutrition-coach-certification-beginner-to-advanced',
        category: 'Nutrition & Diet',
        description:
          'Become A Nutrition Coach: Create Muscle Growth & Fat Loss Meal Plans, Build A Fitness Diet Business & Be A Health Expert',
        image: 'https://img-c.udemycdn.com/course/240x135/1815870_476b.jpg',
        instructor: 'Created by Felix Harder',
        lastUpdated: 'Last updated 9/2022',
        slug: 'course/diet-nutrition-coach-certification-beginner-to-advanced/',
        tag: 'Nutrition',
        title: 'Diet And Nutrition Coach Certification: Beginner To Advanced',
        index: '6353ad2ed4a540a0a489422b',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            '15 vinyasa or "flow" yoga sequences.',
            'Improve your range of motion.',
            'Lubricate your joints.',
            'Release tight muscles.',
            'Improve your cardiovascular health.',
            'Boost your metabolism.',
            'Improve your body composition (ratio of fat to muscle).',
            'Build your stamina.',
            'Increase your agility.',
            'Improve your coordination.',
            'Enhance your focus and concentration.',
            'Boost your mood.',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['This course is suitable for students who have some experience practicing yoga.'],
          descriptionTitle: 'Description',
          courseDescription:
            '<p><em>“Mobility is the body’s own anti-ageing agent. When you bathe each joint in nutritive and lubricative flow, you revitalize.” - Scott Sonnon, martial artist</em></p><p>Are you ready to accelerate your yoga skills? Are you looking for a challenge and some brand new yoga sequences to master?</p><p>In this online yoga course, renowned yoga instructor, founder of <strong>Yoga 15,</strong> and athlete Abi Carver, takes you through a 15-day lesson plan designed to advance your yoga skills, energize your body, improve your mobility and increase your dynamic flexibility. This course is highly effective <em>and</em> efficient and is part 4 of a 5-part series.</p><p>The style of yoga taught in this course is known as <em>vinyasa</em> or flow and it\'s fairly advanced. <em>Vinyasa</em> is a Sanskrit term that means "to place in a specific way". In this series of videos we practice a number of different flows, based around the fundamental yoga poses—Warrior 1, Warrior 2, Warrior 3, Extended Side Angle and Reverse Warrior. At a fairly fast pace. </p><p><strong><em>What can you expect from the course?</em></strong></p><p>In each of the sequences, I&nbsp;will guide you though a continuous series of poses, synchronizing breath and movement and emphasising precise transitions between postures. My method has proven to be highly effective both for my <strong>Yoga 15</strong> students and in my own action-packed daily life. This course will become a longstanding reference for you in improving your yoga skills and feeling better stellar throughout your workweek and into the weekend!</p><p><strong><em>Testimonials on Abi\'s "Yoga 15 Mobility" Course</em></strong></p><p><em>"This was a good match for me and helped me to clear my mind and wake up each morning. When I started work my mind was clear and uncluttered so I could go through my daily tasks and prioritize in a calm and collective manner." Neil Hasegawa-Yates</em></p><p><em>"fantastic!! the first thing I ever do every day is my 15 min of Yoga followed by a meditation, only after that I \'start\' with my day! Abi is every day more beautiful!" Daniel J Esains</em></p><p><em>"I’m really in love of the way she talk. It’s great that she film the sequence and then add the voice afterwards. I feel improvements on my flexibility, balance and strength and I really like this mobility challenge. I’ll probably repeat it. Looking forward more courses, ;) thanks Abi!" Lucía Pérez De La Rubia</em></p><p><em>“This course has helped me with my mobility and recovering from some pain. From following this course consistently, I can also learn how to focus better.” Genieva Croley</em></p><p><em>“GREAT!!!!” Sakshi Shokeen</em></p><p><em>"I like it it s short and u can easily and always find time." Leilaki</em></p><p><em>"I love this course. The mobility challenge is a great way to start my day. \'ve done two other courses by Abi; the strength and introduction course. Her instructions are very concise, and her self-checking tips are on point as always. I feel the difference after completing each exercise, and I see how I\'m gradually progressing. I highly recommend this course to anyone who\'s looking to try out yoga without any of the spiritual woo-woos that some teachers may have. :)" Adelyn</em></p><p><em>"Abi\'s 15 minute routines are perfect for those who need a quick yoga workout at the beginning of a busy day or at the end of a long one. I\'ve tried one hour programs that seem to take up too much time in the morning and resulted in more often than not, me skipping the workout all together. Fifteen minutes is just enough to get a good stretch in to get you ready for the rest of your day." Scott Chin</em></p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Men and women excited to progress their yoga practice.',
            'Unsuitable if you are suffering from injury.',
          ],
        },
        id: 'course-yoga-mobility-challenge-15-minutes-x-15-days-66',
        category: '',
        description:
          'Increase your flexibility and range of motion, energise your body and improve your yoga skills in 15 minutes a day.',
        image: 'https://img-c.udemycdn.com/course/240x135/395170_6eda_3.jpg',
        instructor: 'Created by Abi Carver',
        lastUpdated: 'Last updated 8/2022',
        slug: 'course/yoga-mobility-challenge-15-minutes-x-15-days-66/',
        tag: '',
        title: '15 Minutes x 15 Days Yoga Mobility Challenge',
        index: '6353ad2dd4a540a0a48941a5',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Understand the fundamentals of healthy dieting (calories, protein, carbs, fat, vitamins & minerals)',
            'Create a diet that is perfect for your needs and lifestyle',
            'Learn when, what and how much you should eat for optimal body composition',
            'Build more muscle by optimizing your meal plan',
            'Lose fat faster by optimizing your meal plan',
            'Improve immunity and energy levels with the right vitamins and minerals',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: [
            'No prior health knowledge is required or assumed',
            'A digital food scale will help but is not required',
          ],
          descriptionTitle: 'Description',
          courseDescription:
            "<p><strong>&gt;&gt;Course Regularly Updated With New Lectures &amp; Bonus Content&lt;&lt;</strong></p><p><strong>Learn How To Build The Perfect Diet &amp; Meal Plan For Improved Health, Better&nbsp;Weight Loss&nbsp;And More&nbsp;Muscle Gains</strong></p><p>Hi,&nbsp;I'm Felix Harder fitness and dieting coach and amazon best selling author.&nbsp;My \"Nutrition Masterclass\"&nbsp;is designed <strong>for anyone&nbsp;who wants to get the most out of their diet</strong>, no matter if you're an athlete, bodybuilder or simply want to live a healthier life.</p><p>This course is not some random fad&nbsp;diet that tells you which foods you should and shouldn't&nbsp;eat. Instead I will <strong>take you&nbsp;through each of the steps involved in setting up and following through with your diet</strong>.&nbsp;</p><p>Unfortunately, the internet is full of false health gurus that sell you all kinds of diet plans and supplements that are overpriced and don't work. This is why I wanted to create a video course that not only debunks the most common dieting myths but also <strong>teaches everything you need to know to reach your dieting goals, be it to lose fat, build muscle or simply live a healthier life.&nbsp;</strong><br></p><p>Here Is What's Inside The Program<strong>:</strong><br></p><p><strong>Dieting For Health &amp; Fitness</strong></p><ul><li><p><em>Everything You Need To Know About Calories,&nbsp;Protein, Carbs &amp; Fat</em></p></li><li><p><em>How To Determine Your Optimal Calorie Intake</em></p></li><li><p><em>How To Track Calories The Right Way</em></p></li><li><p><em>How To&nbsp;Adjust Your Diet For Weight Loss</em></p></li><li><p><em>How To&nbsp;Adjust&nbsp;Your Diet For Muscle Gains</em></p></li><li><p><em>The Perfect Pre- &amp; Post-Workout Meals</em>&nbsp;</p></li><li><p><em>Cheat Meals That Won't Destroy&nbsp;Your Overall&nbsp;Diet&nbsp;</em></p></li><li><p><em>Ready To Use Meals Plans To Lose Weight And Build Muscle&nbsp;</em></p></li></ul><p><strong>Diet Trends&nbsp;Explained (See If They Are Right For You):</strong></p><ul><li><p><em>Gluten Free</em></p></li><li><p><em>Low Carb</em></p></li><li><p><em>Paleo Dieting</em></p></li><li><p><em>Intermittent Fasting</em></p></li><li><p><em>Vegan Dieting</em></p></li></ul><p><strong>Everything You Need To Improve Your Health &amp; Immunity:</strong></p><ul><li><p><em>The Right&nbsp;Vitamins &amp; Minerals</em></p></li><li><p><em>How Much Water You&nbsp;Should Really Drink (No, It's Not 8 Glasses Per Day)</em></p></li><li><p><em>How To Boost Testosterone Naturally</em></p></li><li><p><em>How To Correctly&nbsp;Read A Nutrition Label</em></p></li><li><p><em>Scientifically Proven Ways To Boost Immunity</em></p></li></ul><p><strong>Common Dieting&nbsp;Questions Answered:</strong></p><ul><li><p><em>Are&nbsp;Carbs&nbsp;Bad For You?</em></p></li><li><p><em>Is Too Much&nbsp;Fat Bad For You?</em></p></li><li><p><em>Is Too Much Protein Bad For You?</em></p></li><li><p><em>Do Eggs Really Raise Cholesterol?</em></p></li><li><p><em>Does Meat Cause Cancer?</em></p></li><li><p><em>Do Several Small Meals Throughout The Day&nbsp;Boost Your Metabolism?</em></p></li></ul><p><strong>All In All The Program Includes Over 80 Lessons On Dieting And Nutrition</strong></p><p><strong>So If You Want To&nbsp;Boost Your&nbsp;Performance,&nbsp;Feel More Energized And&nbsp;Live A Healthier Life, This Is The Right Course For You</strong></p><p>Learn about proper superfoods nutrition, meal planning, healthy eating and a healthy lifestyle. Better meal planning and healthy cooking will help with weight loss, building muscle and overall well being. </p><p>Remember, there is a 30-day 100% money-back guarantee. There is no reason to hesitate. Enroll now, see if you enjoy the course, and <strong>start building your perfect&nbsp;diet today</strong>!</p>",
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone wanting to learn the truth about dieting & meal planning',
            'Anyone with an open mind towards dieting',
          ],
        },
        id: 'course-nutrition-masterclass-build-your-perfect-diet-meal-plan',
        category: 'Nutrition & Diet',
        description:
          'Learn The Truth About Nutrition, Dieting For Weight Loss, Building Muscle, Healthy Eating, Meal Planning, Fat Loss',
        image: 'https://img-c.udemycdn.com/course/240x135/1289968_6b08_2.jpg',
        instructor: 'Created by Felix Harder',
        lastUpdated: 'Last updated 9/2022',
        slug: 'course/nutrition-masterclass-build-your-perfect-diet-meal-plan/',
        tag: 'Nutrition',
        title: 'Nutrition Masterclass: Build Your Perfect Diet & Meal Plan',
        index: '6353ad2ed4a540a0a4894237',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Learn to use the breath to relax, focus and bring health and vitality in your life. Use the breath as a tool to become a master of mind and body',
            'Learn basic and advanced breathwork and meditation techniques. Tap into the power of your breath!',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: [
            'A breathing/ breathwork course for people for anyone wanting to learn profound breathing techniques. From people that are new to breathing practices to yoga instructors or professional athletes. A breathing course for everyone.',
          ],
          descriptionTitle: 'Description',
          courseDescription:
            '<p>The most extensive breathwork course available on Udemy. Get a profound understanding of breathwork and meditation and learn how to use your breath like a wonderful tool to start controlling all systems in your body. Take care of your mind and how to take the awareness to the Soul level and realize your true nature.<em>&nbsp; &nbsp;</em> <br><br><em>(I believe these techniques should be available for everybody, money or no money. If you have no money to do the course you can PM me and we will find a solution)&nbsp; &nbsp; &nbsp; </em></p><p><em>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </em></p><p><em>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </em><strong><em>" Proper breathing is the foundation of healthy living "&nbsp; </em></strong></p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;This breathing course is guided by founder of the Life Awareness Project, Michaël Bijker</p><p><br></p><p>(This course is mostly the same course as the \'Breath is Life\' Pranayama &amp;&nbsp;Meditation course)<br>In this wonderful Yogic breathing (Pranayama),&nbsp; breathwork and meditation course you will learn how to use the power of the breath to:</p><ul><li><p>Clear you mind and sharpen your awareness</p></li><li><p>Increase energy, health and mental balance</p></li><li><p>Energize or calm your body and mind</p></li><li><p>Become aware of the deeper layers of the self</p></li></ul><p><strong>Techniques learned in this Pranayama breathwork course:</strong></p><ul><li><p>Explanation about meditation and how to use the breath to still the mind and sharpen the awareness</p></li><li><p>Energy and consciousness awakening breathing technique</p></li><li><p>Yogic Breathing - Open up the energy systems</p></li><li><p>Ocean breathing (Ujjayi Pranayama) - Create inner silence</p></li><li><p>Breath of fire (Bhastrika Pranayama) - Awaken the fire within</p></li><li><p>Energy Locks (Bandhas)</p></li><li><p>Skull cleansing breath - Cleaning of the systems in mind and body</p></li><li><p>Kaki mudra Pranayama - Focusing the mind</p></li><li><p>Energy cleansing technique (Nadi Shodhana/ Anulom Vilom Pranayama)</p></li><li><p>Cosmic Breathing (Pranava Pranayama) </p></li><li><p>Bhramari Pranayama</p></li><li><p>Udgeeth Pranayama - Connecting with a higher Self</p></li><li><p>Guided meditations, breathing and mind training sessions</p></li><li><p>Bandhas (Body/ energy locks)</p><p><br></p><p><br><em> &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</em><br>This course will give you the tools to tap into the power of the mind and change your life.<br><br><br><strong>Benefits of this breathwork course</strong></p><ul><li><p>Boost your immune system</p></li><li><p>A boost in energy levels</p></li><li><p>Deep &amp; restorative sleep</p></li><li><p>Brain empowerment &amp; better focus</p></li><li><p>Relieves stress, anxiety &amp; depression</p></li><li><p>Heal mind &amp; body<br></p></li></ul><p><strong>Who is this course for?</strong></p><ul><li><p>For complete beginners and advanced practitioners.</p></li><li><p>A perfect course for Yoga practitioners &amp; teachers, Meditation practitioners &amp; teachers to deepen their practice.</p></li><li><p>Essential for athletes, athletes, healers, life coaches.</p></li><li><p>Treating insomnia, depression, overthinking, low energy, addiction restlessness and for those that want to train the mind and awareness.</p></li><li><p>Everyone that wants to get stronger, healthier and happier<br></p></li></ul><p><strong>What is included in this pranayama &amp;&nbsp;breathwork course?</strong></p><ul><li><p>VIDEO TUTORIALS - Access to over 60 online guided breathwork and mind training sessions (over 15 hours of HD video material) accessible anywhere at any time.</p></li><li><p>GUIDED&nbsp;MEDITATION&nbsp;&amp;&nbsp;BREATHWORK&nbsp;SESSIONS - A great variety of different pranayama and meditation sessions for different purposes.</p></li><li><p>WARMUP &amp; EXERCISE VIDEOS - Choose from several physical exercise videos to open up, strengthen and prepare the body for the breathing practices.</p></li><li><p>LIFETIME ACCESS - Learn these wonderful mind training and breathing techniques at your own pace, you will have a lifetime access to this course, so take your time.</p></li><li><p>BRAIN ENHANCING AUDIO - 3 audio sessions for healing, sleeping and pineal gland activation</p></li><li><p>CERTIFICATION UPON COMPLETION - When you complete this online Pranayama course, you will receive a certificate of completion.<em><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </em></p></li></ul></li></ul>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Everyone that wants to learn more about the power of breathing and meditation.',
            'People that want to learn the techniques of breathwork to create a better, healthier and more empowered life.',
          ],
        },
        id: 'course-breathing',
        category: 'General Health',
        description:
          'Tap into the power of your breath and develop health, happiness and inner richness. A complete breathwork course.',
        image: 'https://img-c.udemycdn.com/course/240x135/2027448_0785_6.jpg',
        instructor: 'Created by Michaël Bijker',
        lastUpdated: 'Last updated 5/2022',
        slug: 'course/breathing/',
        tag: 'Breathing Techniques',
        title: '"Breath is Life" Breathwork & Meditation course',
        index: '6353ad2ed4a540a0a489425c',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Earn your CPD Certificate',
            'Help others lose fat & build muscle',
            'Assess clients and determine fitness & strength levels',
            'Create individual workouts and exercise programs',
            'Understand the fundamentals of human anatomy',
            'Know correct movement form for the most important exercises',
            'Build and grow a coaching business (online or in person)',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['Willingness to help and motivate others to exercise', 'Passion for fitness'],
          descriptionTitle: 'Description',
          courseDescription:
            '<p><strong>&gt;&gt;&gt;THIS COURSE IS CPD ACCREDITED. COMPLETE IT AND YOU AUTOMATICALLY EARN YOUR CERTIFICATION &amp; 10 CREDITS&lt;&lt;&lt;</strong></p><p><strong>Learn How To Become A Fitness Trainer, Work With Clients And Grow&nbsp;Your&nbsp;Fitness Coaching&nbsp;Business </strong></p><p>Hi,&nbsp;I\'m Felix Harder fitness coach and certified nutritionist.&nbsp;My "Complete Fitness Trainer Certification"&nbsp;is designed&nbsp;<strong>for anyone&nbsp;who wants to coach others about fitness training - be it&nbsp;cardio, strength training or flexibility.</strong></p><p>In this course I will take you through the process of <strong>becoming a fitness expert&nbsp;step by step</strong>. You will learn everything you need to know about the fundamentals of good training programs and how to design your very own for you or your clients.&nbsp;</p><p>Researching and gathering all the knowledge you need to coach others takes a lot of time, so I created this course as a <strong>complete program to teach you everything there is to know about the three pillars of a good fitness workout</strong>:</p><p>- Strength training (e.g. gym training or bodyweight training)<br>- Cardiovascular training (e.g. jogging, circuit training or HIIT)<br>- Flexibility (e.g.&nbsp;stretching and maintaining healthy joints)</p><p><strong>Here Is What\'s Inside The Program:\n</strong></p><p><strong>Human Anatomy</strong></p><ul><li><p><em>The Nervous System Explained</em></p></li><li><p><em>The Skeletal System Explained</em></p></li><li><p><em>The Muscular System Explained</em></p></li><li><p><em>The Cardiovascular System Explained</em></p></li><li><p><em>The Different Types Of Muscle Fibers</em></p></li><li><p><em>How Muscles Contract&nbsp;&amp; What Makes Them Grow</em>&nbsp;</p></li><li><p><em>Muscle Agonists &amp; Antagonists&nbsp;&nbsp;</em></p></li></ul><p><strong>Client Assessment&nbsp;(Determine Strength &amp; Fitness Levels)</strong></p><ul><li><p><em>The Client Interview</em></p></li><li><p><em>Fitness Assessment</em></p></li><li><p><em>The&nbsp;Harvard Step Test</em></p></li><li><p><em>Estimating 1 Rep Max Strength</em></p></li></ul><p><strong>Resistance Training</strong></p><ul><li><p><em>How To Build A Beginner Gym&nbsp;Workout</em></p></li><li><p><em>Bodyweight vs Strength Training</em></p></li><li><p><em>My&nbsp;Muscle Building Formula</em></p></li><li><p><em>My Fat Loss&nbsp;Formula</em></p></li><li><p><em>The 4 Most Important Exercises For Muscle Growth</em></p></li><li><p><em>How To Warm Up Before Lifting Weight</em></p></li></ul><p><strong>Exercise Videos (Learn Proper Form)</strong></p><ul><li><p><em>Bench Press</em></p></li><li><p><em>Deadlift</em></p></li><li><p><em>Squats</em></p></li><li><p><em>Lat Pull-Downs</em></p></li><li><p><em>Barbell Rows</em></p></li><li><p><em>Push-Ups</em></p></li><li><p><em>Pull-Ups</em></p></li><li><p><em>Chin-Ups</em></p></li><li><p><em>Lunges</em></p></li></ul><p><strong>Cardio &amp; Endurance Training</strong></p><ul><li><p><em>How To Build A&nbsp;Cardio Workout</em></p></li><li><p><em>The Different Types Of Cardio</em></p></li><li><p><em>How To Measure Your Heart Rate During A Workout</em></p></li><li><p><em>Cardio vs Weight training - Which Is Better For Weight Loss?</em></p></li><li><p><em>The Right&nbsp;Cardio For Weight Loss</em></p></li><li><p><em>HIIT Explained (incl. Sample Workout)</em></p></li></ul><p><strong>Flexibility</strong></p><ul><li><p><em>Most Common Stretching Mistakes</em></p></li><li><p><em>Static vs Dynamic Stretching</em></p></li><li><p><em>Sample Stretching Routine</em></p></li></ul><p><br></p><p>This course will give you<strong> all the tools you need to help others achieve their fitness goals,</strong> be it to build muscle, lose fat or simply life a more active life. If you want to <strong>build up your online fitness coaching business, be it online or in person</strong> it’s important you equip yourself with the knowledge of how to correctly work with your students and understanding their painpoints.</p><p>The fitness coach course is designed to develop both your personal and professional life. That means it’s not just for professionals but also for beginners who want to improve their own fitness level. <strong>You don’t have to have to be a personal fitness trainer or have any students yet and all you need is an interest in fitness to get started.</strong></p><p>The program is made up of multiple downloadable worksheets, eBooks and other printable resources. If you sign up you get access to all of them so you can <strong>study anywhere and at anytime</strong>.&nbsp;</p><p><strong>So If You Want To&nbsp;Coach Others And&nbsp;Make Fitness Your Career,&nbsp;This Is The Right Course For You</strong></p><p>Remember, there is a 30-day 100% money-back guarantee. There is no reason to hesitate. Enroll now, see if you enjoy the course, and&nbsp;<strong>start learning today</strong>!</p><p><br></p>',
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone interested in coaching others',
            'Anyone wanting to learn how to design fitness workouts',
            'Anyone wanting to grow their fitness business (online or in person)',
          ],
        },
        id: 'course-complete-fitness-trainer-certification-beginner-to-advanced',
        category: '',
        description:
          'Become A Fitness Coach: Create Muscle Growth & Fat Loss Workouts, Build A Fitness Training Business & Be A Health Expert',
        image: 'https://img-c.udemycdn.com/course/240x135/1754344_cbff.jpg',
        instructor: 'Created by Felix Harder',
        lastUpdated: 'Last updated 9/2022',
        slug: 'course/complete-fitness-trainer-certification-beginner-to-advanced/',
        tag: '',
        title: 'Complete Fitness Trainer Certification: Beginner To Advanced',
        index: '6353ad2ed4a540a0a48941e2',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'Learn active sitting techniques',
            'Incorporate 5 office exercise routines',
            'Release nagging neck tension',
            'Restore spinal flexibility',
            'Understand and implement good office ergonomics',
            'Improve attractiveness and self image',
            'Achieve more success at work',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: [
            'A job where you are sitting sedentary for hours at a time',
            'A few minutes a day to release your tension',
            'No fancy equipment needed',
            'Motivation to exercise at work',
          ],
          descriptionTitle: 'Description',
          courseDescription:
            "<p><strong>Over 15,000 Students Enrolled!</strong></p><p>_____________________________________________________</p><p>Updated to include specific steps for anyone working at home due to Corona changes.</p><p>_____________________________________________________</p><p><br></p><p><strong>Course Description</strong></p><p>If you sit at a desk for hours at a time, then this course is perfect for you.</p><p>Not only can you use this time to actually benefit your health and your posture, but you can also take positive steps to avoid bad backs, tense necks, and sore legs, arms, and knees.</p><p>This online office exercise course will teach you how to sit less and move more, using <em>active</em> sitting.</p><p><br></p><p>This course is designed to undo the damaging effects of prolonged sitting, even if you have little to no experience with exercise, and will help you feel more energetic, confident and attractive, and even more successful at work!</p><p><br></p><p>While there are plenty of fitness and/or posture courses that focus on specific styles or how to get rid of pain, here you'll find a practical, usable course, which specifically targets the needs of any desk-based office worker.</p><p><br></p><p>This course is designed for all ages and body types. What is important is that you want to address your sedentary lifestyle and improve your posture while you work.</p><p><br></p><p>I invite you to&nbsp;join me now.</p><p>Thank you and I really look forward to seeing you inside the course.</p><p><br></p><p>Your posture doc,</p><p>Paula Moore</p>",
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'Anyone who sits for prolonged periods each day',
            'Anyone who wants to sit less and move more',
            'Desk-bound office workers',
            'Anyone who worries about the effects of prolonged sitting',
            'Anyone who wants more energy, attractiveness and success!',
          ],
        },
        id: 'course-sit-less-move-more-office-desk-exercise-to-improve-posture',
        category: 'General Health',
        description: 'Helping employees become more active and far more comfortable',
        image: 'https://img-c.udemycdn.com/course/240x135/430228_26e5_3.jpg',
        instructor: 'Created by Posture Videos',
        lastUpdated: 'Last updated 8/2022',
        slug: 'course/sit-less-move-more-office-desk-exercise-to-improve-posture/',
        tag: 'Posture',
        title: 'Sit Less Move More - Office Desk Exercise To Improve Posture',
        index: '635429b1d4a540a0a4ffb820',
      },
      {
        content: {
          title: "What you'll learn",
          description: [
            'By taking this course, you will learn, step by step, how to teach fun, engaging and safe yoga classes to children of all ages, from 2-17 years!',
            'Learn what the best yoga poses for each age group are - this course includes beautifully illustrated kids yoga pose guides for you to print out and keep!',
            'Learn the 5 steps to creating your own super fun kids yoga stories for kids aged 2-8 years',
            'Find out how to keep kids engaged and having fun in your yoga classes',
            'Understand the physical, mental and emotional development of each age group and how it relates to the kids doing yoga',
            'Learn to teach guided mindfulness meditations, relaxation practices and breathing exercises to kids',
            'Yoga games and activities - learn what yoga games and activities each age group enjoys',
            'Yoga sequencing - once children are aged over 8 they will love getting started with yoga sequences! This course provides you with sequences to teach to kids',
            'Learn how yoga can help children to deal with stress, worry and anxiety',
            'Learn the business of yoga! We have dedicated one full module on how to get your kids yoga classes into kindergartens, pre-schools, schools and yoga studios!',
          ],
          requirementsTitle: 'Requirements',
          requirementsDescription: ['No. There are no requirements to take this course. Anybody can teach kids yoga!'],
          descriptionTitle: 'Description',
          courseDescription:
            "<p>If you want to learn how to teach fun yoga classes to kids of all ages, then you are in the right place! </p><p>This course will give you all of the skills, knowledge, resources and confidence you will need to start teaching yoga to kids, today!</p><p>This course delivers all of the need-to-know information about children's development and how it relates to learning yoga, you will learn how to teach excellent yoga classes that keep kids fully engaged and having fun.</p><p>You will be provided with exclusive Peaceful Babes, printable resources, including:</p><ul><li><p>A beautifully illustrated, Kids Yoga Pose Guide - one for each separate age group from ages 2 to 17</p></li><li><p>A fully illustrated, 90 page, pose by pose guide, that includes pose pictures, instructions and benefits</p></li><li><p>Beautifully designed, printable guided meditations, breathing practices and relaxation practices for each age group</p></li><li><p>Exclusive, Peaceful Babes, kids coloring in sheets to hand out to your yoga students</p></li><li><p>Printable class plans</p></li><li><p>And much more!</p></li></ul><p>The resources you will receive when you enroll in this course are exclusive to Peaceful Babes and are not offered by any other course worldwide!</p><p>You will also learn the, Peaceful Babes, 5 steps to creating fun yoga stories, plus tips on how to perform an incredible kids yoga story that keeps kids fully engaged and having a great time!</p><p>In addition to learning how to teach fun yoga classes to kids, you will also learn the business of kids yoga! The final module of this course is fully dedicated to showing you exactly how to earn a full time income from teaching yoga classes to kids, anywhere in the world!</p><p>By the end of this course you will have the knowledge, skills and resources to confidently start to teach super fun, engaging and safe kids yoga classes to children of all ages.</p><p>You need no prior knowledge to take this course, complete beginners are welcome!</p><p>Enroll today!</p>",
          targetAudienceTitle: 'Who this course is for:',
          targetAudienceDescription: [
            'This course is designed for complete beginners through to qualified teachers and yoga instructors.',
            'You may be a yoga instructor who wishes to increase their skills and knowledge so that you can offer kids yoga classes at yoga studios, in kindergartens, schools or within your community.',
            'You may be a teacher who would like to introduce yoga and mindfulness activities into your classroom.',
            'You may be a parent or carer who wishes to learn how to teach yoga and mindfulness to your children or to the children in your care.',
            'Or you may be somebody with no prior yoga or teaching experience but you would still love to teach yoga and mindfulness yo kids in kindergartens in in your community, this course is for you too!',
          ],
        },
        id: 'course-kids-yoga-teacher-training-certificate-course',
        category: 'Yoga',
        description:
          'Confidently teach fun, safe and engaging yoga classes to kids aged 2 to 17 years - Kids Yoga Business Training included!',
        image: 'https://img-c.udemycdn.com/course/240x135/2709124_745b_3.jpg',
        instructor: 'Created by Jessica Fleming',
        lastUpdated: 'Last updated 6/2021',
        slug: 'course/kids-yoga-teacher-training-certificate-course/',
        tag: 'Yoga for Kids',
        title: 'Kids Yoga Teacher Training Certificate Course - Ages 2-17',
        index: '635429b1d4a540a0a4ffb833',
      },
    ],
    page: 1,
    limit: 12,
    totalPages: 41,
    totalResults: 490,
  },
};

/**
 * Fetch courses data
 */
export const fetchCourses = (): Object => {
  return data;
};

/**
 * Fetch courses data
 */
export const fetchCourseBySlug = (slug: string): {} | undefined => {
  const courseData = data.data.results.find((item) => item.slug.includes(slug));
  return courseData;
};
